name: 🚀 Deploy 12.3

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/ci.yml
    with:
      version: "12.3"
    secrets: inherit
